image: registry.rev.ng:443/fcremo/orchestra-v3:latest

stages:
  - build

create-binaries:
  stage: build
  script:
  - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  - .orchestra/ci/install-dependencies.sh
  - git remote add internal https://gitlab-ci-token:${CI_JOB_TOKEN}@rev.ng/gitlab/revng-internal/orchestra-v3.git || true
  - git remote add private https://gitlab-ci-token:${CI_JOB_TOKEN}@rev.ng/gitlab/revng-private/orchestra-v3.git || true
  - ./orchestra.py components
  - ./orchestra.py -b install --create-binary-archives ui/cold-revng
