#@ load("@ytt:template", "template")

#@ load("/components/macos/libtapi.lib.yml", "libtapi_component")
#@ load("/components/macos/sdk.lib.yml", "macosx_sdk_component")
#@ load("/components/macos/ld64.lib.yml", "ld64_components")
#@ load("/components/macos/clang.lib.yml", "macosx_clang_components")

#@ def _macos_toolchain_components():
macos/libtapi: #@ libtapi_component
macos/sdk: #@ macosx_sdk_component
_ : #@ template.replace(ld64_components)
_ : #@ template.replace(macosx_clang_components)
#@ end

---
#@ macos_toolchain_components = _macos_toolchain_components()
