#@ sdk_archive_name = "Xcode_9.xip-MacOSX.sdk.tar.gz"

#@yaml/text-templated-strings
---
#@ def _macosx_sdk_component():
builds:
  default:
    configure: ""
    install: |
      echo "TODO: macosx sdk" && exit 1
      create-package.sh Xcode_9.xip
      extract.sh --into "${TMP_ROOT}${ORCHESTRA_ROOT}" --src-archive-dir "$SDK_ARCHIVE_DIR" "(@= sdk_archive_name @)"
dependencies:
  - cmake
  - clang-release
  - toolchain/host/gcc
additional_path: "$ORCHESTRA/helpers/repackage-apple-sdk"
#@ end

---
#@ macosx_sdk_component = _macosx_sdk_component()
