#@ load("/components/toolchain/lib/toolchain.lib.yml", "create_toolchain_components")

#@ def _params():
toolchain_name: aarch64
triple: aarch64-unknown-linux-musl
linux_arch_name: arm64
linux_version: "4.14.18"
binutils_version: "2.35"
gdb_version: "8.2.1"
musl_version: "1.1.19"
gcc_version: "7.3.0"
coreutils_version: "8.29"
extra_gcc_configure_options:
  - --without-cloog
  - --without-isl
  - --disable-libsanitizer
  - --disable-libssp
  - --disable-shared
dynamic: "0"
#@ end

---

#@ aarch64_toolchain_components = create_toolchain_components(**_params())
