#@ load("/lib/make.lib.yml", "make")
#@ load("/lib/shell.lib.yml", "expand_args")
#@ load("/lib/optimization_flavors.lib.yml", "qt_optimization_flavors")

#@ load("/global_options.lib.yml", "options")

#@yaml/text-templated-strings
---
#@ def _configure_base(extra_qmake_options=""):
- |
  mkdir -p "$BUILD_DIR"
  cd "$BUILD_DIR";
  $SOURCE_DIR/configure \
    -recheck-all \
    -prefix "$ORCHESTRA_ROOT" \
    -confirm-license \
    -opensource \
    -skip qt3d \
    -skip qtactiveqt \
    -skip qtandroidextras  \
    -skip qtcanvas3d  \
    -skip qtcharts  \
    -skip qtconnectivity  \
    -skip qtdatavis3d  \
    -skip qtgamepad  \
    -skip qtimageformats  \
    -skip qtlocation  \
    -skip qtmacextras  \
    -skip qtmultimedia  \
    -skip qtnetworkauth  \
    -skip qtpurchasing  \
    -skip qtremoteobjects  \
    -skip qtscript  \
    -skip qtscxml  \
    -skip qtsensors  \
    -skip qtserialbus  \
    -skip qtserialport  \
    -skip qtsvg  \
    -skip qtspeech  \
    -skip qttools  \
    -skip qttranslations  \
    -skip qtvirtualkeyboard  \
    -skip qtwebchannel  \
    -skip qtwebsockets  \
    -skip qtwebview  \
    -skip qtwinextras  \
    -skip qtxmlpatterns  \
    -skip qtwebengine \
    -openssl-runtime \
    -no-glib \
    -qt-zlib \
    -no-cups \
    -no-gtk \
    -qt-harfbuzz \
    -fontconfig \
    -system-freetype \
    -opengl desktop \
    -egl \
    -no-eglfs \
    -xkb \
    -qt-xcb \
    -no-icu \
    -libinput \
    -qt-libpng \
    -qt-libjpeg \
    -qt-sqlite \
    -qt-pcre \
    -qt-zlib \
    -qt-doubleconversion \
    -sql-sqlite \
    -no-sql-odbc \
    -no-compile-examples \
    -nomake tests \
    -nomake examples \
    -c++std c++14 \
    -platform linux-clang \
    (@= extra_qmake_options @) \
    QMAKE_CXXFLAGS+="-ggdb3 (@= options["regular_cxx_flags"] @)" \
    QMAKE_LFLAGS+="-ggdb3 (@= options["regular_linker_flags"] @) -Wl,-rpath,(@= options["rpath_placeholder"] @)/lib"
#@ end

#@ def configure_base(**kwargs):
#@    return _configure_base(**kwargs)[0]
#@ end


#@yaml/text-templated-strings
---
#@ def _qt_component():
default_build: optimized
builds:
  #@ for flavor, opts in qt_optimization_flavors.items():
  #@ extra_qmake_options = opts["extra_qmake_options"]
  (@= flavor @):
    configure: |
      extract.sh --into "$SOURCE_DIR" https://download.qt.io/official_releases/qt/5.14/5.14.1/single/qt-everywhere-src-5.14.1.tar.xz
      patch-if-exists "${PATCH_DIR}/qt-5.13.1-libcxx-include-array-linuxdmabuf.patch" "$SOURCE_DIR"

      (@= configure_base(extra_qmake_options=extra_qmake_options) @)
    install: |
      cd "$BUILD_DIR"

      (@= make @)
      (@= make @) install INSTALL_ROOT=$TMP_ROOT

      rm "${TMP_ROOT}${ORCHESTRA_ROOT}/lib64/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"
      touch "${TMP_ROOT}${ORCHESTRA_ROOT}/lib64/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"
      find "${TMP_ROOT}${ORCHESTRA_ROOT}" \( -name "*.pri" -or -name "*.pc" -or -name "*.pri"  \) \
          -exec sed 's|/[^; ]*/lib\([^; ]*\)\.so|-l\1|g' {} -i ";"

      cat > "${TMP_ROOT}${ORCHESTRA_ROOT}/bin/qt.conf" <<EOF
      [Paths]
      Prefix = $ORCHESTRA_ROOT
      EOF
  #@ end
dependencies:
  - clang-release
  - toolchain/host/gcc@stage2
#@ end

---

#@ qt_component = _qt_component()
