#@ load("/lib/optimization_flavors.lib.yml", "typical_project_flavors")
#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

#@ load("/global_options.lib.yml", "options")

---
#@ def build_args():
extra_cmake_args:
  - -DQML_PLUGIN_INSTALL_DIRECTORY="$ORCHESTRA_ROOT/qml"
build_dependencies:
  - cmake
dependencies:
  - toolchain/host/gcc
  - clang-release
  - ui/qt
use_asan: false
#@ end

---
#@ def _quickqanava_component():
repository: ui/quickqanava
builds: #@ typical_cmake_builds(**build_args())
#@ end

---
#@ quickqanava_component = _quickqanava_component()
