#@ load("/lib/optimization_flavors.lib.yml", "typical_project_flavors")
#@ load("/lib/cmake.lib.yml", "cmake_boost_configuration", "typical_cmake_builds")

#@ load("/global_options.lib.yml", "options")

---
#@ def build_args():
extra_cmake_args: #@ cmake_boost_configuration
build_dependencies:
  - cmake
dependencies:
  - clang-release
  - llvm
  - revng
  - revng-c
  - boost
use_asan: false
#@ end

---
#@ def _caliban_component():
repository: caliban
builds: #@ typical_cmake_builds(**build_args())
#@ end

---
#@ caliban_component = _caliban_component()
