#@ load("/lib/create_component.lib.yml", "single_build_component")

#@yaml/text-templated-strings
---
#@ def _revng_qa_args():
repository: revng-qa
configure: |
  mkdir -p "$BUILD_DIR"
  cd "$BUILD_DIR"; \
  cmake "$SOURCE_DIR" \
    -DCMAKE_INSTALL_PREFIX="$ORCHESTRA_ROOT" \
    -DTRIPLE_x86_64="x86_64-gentoo-linux-musl" \
    -DTRIPLE_mips="mips-unknown-linux-musl" \
    -DTRIPLE_mipsel="mipsel-unknown-linux-musl" \
    -DTRIPLE_i386="i386-gentoo-linux-musl" \
    -DTRIPLE_arm="armv7a-hardfloat-linux-uclibceabi" \
    -DTRIPLE_aarch64="aarch64-unknown-linux-musl" \
    -DTRIPLE_s390x="s390x-ibm-linux-musl"
build_system: make
dependencies:
  - cmake
  - clang-release
  - qemu
  - toolchain/x86-64/gcc@stage2
  - toolchain/i386/gcc@stage2
  - toolchain/arm/gcc@stage2
  - toolchain/aarch64/gcc@stage2
  - toolchain/s390x/gcc@stage2
  - toolchain/mips/gcc@stage2
  - toolchain/mipsel/gcc@stage2
#@ end

---

#@ revng_qa_component = single_build_component(**_revng_qa_args())
