#@data/values
---
parallelism: "16"
build_from_source: []
paths:
  #! orchestra_root: /absolute/path/only
  #! source_archives: /absolute/path/only
  #! binary_archives: /absolute/path/only
  #! tmproot: /absolute/path/only
  #! sources_dir: /absolute/path/only
  #! builds_dir: /absolute/path/only
