#@ sdk_archive_name = "Xcode_9.xip-MacOSX.sdk.tar.gz"

#@yaml/text-templated-strings
---
#@ def _macosx_sdk_component():
builds:
  default:
    configure: |
      mkdir -p "$BUILD_DIR"
    install: |
      # echo "TODO: macosx sdk" && exit 1
      # create-package.sh Xcode_9.xip
      extract.sh --into "${TMP_ROOT}${ORCHESTRA_ROOT}" "(@= sdk_archive_name @)"
    build_dependencies:
      - cmake
    dependencies:
      - clang-release
      - toolchain/host/gcc
add_to_path: "$ORCHESTRA_DOTDIR/helpers/repackage-apple-sdk"
#@ end

---
#@ macosx_sdk_component = _macosx_sdk_component()
